global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "kubernetes"
    kubernetes_sd_configs:
      - role: node
        api_server: http://psi-k8s:6443
        tls_config:
          insecure_skip_verify: true

  - job_name: "kafka"
    static_configs:
      - targets: ["psi-kafka:9092"]

  - job_name: "opensearch"
    static_configs:
      - targets: ["psi-opensearch:9200"] 